title:              flip.sphere
titleFlip:          flip
titleDiv:           .
titleSphere:        Sphere
description:        A web development blog by Natalie de Weerd
author:             Natalie de Weerd
baseurl:            "/"

# Social Profiles
github_username:    nataliedeweerd
dev_username:       nataliedeweerd

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-31151002-2 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
